# Generated by Django 5.2.7 on 2026-03-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500, verbose_name='کاربر')),
                ('chat_history', models.TextField(verbose_name='سابقه چت')),
            ],
            options={
                'verbose_name': 'چت',
                'verbose_name_plural': 'چت ها',
            },
        ),
    ]
