# Generated by Django 5.2.7 on 2026-03-03 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='current_date_time',
            field=models.CharField(default='1404/12/12 10:37', max_length=20, verbose_name='ساعت و تاریخ شمسی کنونی مکالمه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conversation',
            name='chat_history',
            field=models.TextField(verbose_name='تاریخچه مکالمه'),
        ),
    ]
