# Generated by Django 5.2.7 on 2026-03-04 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_conversation_current_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='chat_history',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='current_date_time',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messager', models.CharField(choices=[('پاسخ هوش مصنوعی', 'پاسخ هوش مصنوعی'), ('پیام کاربر', 'پیام کاربر')], max_length=50, verbose_name='ارسال کننده')),
                ('body', models.TextField(verbose_name='پیام')),
                ('current_date_time', models.CharField(max_length=20, verbose_name='ساعت و تاریخ شمسی پیام')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='page.conversation', verbose_name='چت')),
            ],
            options={
                'verbose_name': 'پیام',
                'verbose_name_plural': 'پیام ها',
            },
        ),
    ]
