# Generated by Django 5.2.7 on 2026-03-04 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_remove_conversation_chat_history_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'verbose_name': 'گفت و گو', 'verbose_name_plural': 'گفت و گو ها'},
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_messages', to='page.conversation', verbose_name='گفت و گو'),
        ),
    ]
