# Generated by Django 5.2.7 on 2026-09-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='title',
            field=models.CharField(default='title', max_length=500, verbose_name='عنوان'),
            preserve_default=False,
        ),
    ]
