# Generated by Django 5.2.7 on 2026-09-23 07:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_conversation_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='توکن گفتگو'),
        ),
    ]
